version: '3.8'

services:
  frontend:
    build:
      context: ./app/frontend/pyeye
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DATABASE_URL=postgresql://admin:admin@database:5432/postgres
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/letsencrypt

networks:
  app-network:
    driver: bridge