version: '3.8'

services:
  frontend:
    build:
      context: ./app/frontend/pyeye
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./app/backend
    ports:
      - "8000:8000"
    env_file:
      - config.env
