version: '3.8'

services:
  frontend:
    build:
      context: ./app/frontend/pyeye
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build:
      context: ./app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge