version: '3.8'

services:
  frontend:
    build:
      context: ./app/frontend/pyeye
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./app/backend
    ports:
      - "8000:8000"
    env_file:
      - config.env
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/letsencrypt